# Generated by Django 5.2.6 on 2025-11-03 12:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_news_image_alter_news_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Video file', max_length=255, null=True, verbose_name='video'),
        ),
    ]
